name: Test Transfer Issue and Comment
on: [push]

jobs:
  test-action:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: Look at System
        run: pwd
        run: ls
  